/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpdaterRouteImport } from './routes/updater'
import { Route as TutorialInstallRouteImport } from './routes/tutorial-install'
import { Route as MaknaKataRouteImport } from './routes/makna-kata'
import { Route as GlosariumRouteImport } from './routes/_glosarium'
import { Route as GlosariumIndexRouteImport } from './routes/_glosarium.index'
import { Route as GlosariumCariMaknaRouteImport } from './routes/_glosarium.cari-makna'

const UpdaterRoute = UpdaterRouteImport.update({
  id: '/updater',
  path: '/updater',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorialInstallRoute = TutorialInstallRouteImport.update({
  id: '/tutorial-install',
  path: '/tutorial-install',
  getParentRoute: () => rootRouteImport,
} as any)
const MaknaKataRoute = MaknaKataRouteImport.update({
  id: '/makna-kata',
  path: '/makna-kata',
  getParentRoute: () => rootRouteImport,
} as any)
const GlosariumRoute = GlosariumRouteImport.update({
  id: '/_glosarium',
  getParentRoute: () => rootRouteImport,
} as any)
const GlosariumIndexRoute = GlosariumIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GlosariumRoute,
} as any)
const GlosariumCariMaknaRoute = GlosariumCariMaknaRouteImport.update({
  id: '/cari-makna',
  path: '/cari-makna',
  getParentRoute: () => GlosariumRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof GlosariumIndexRoute
  '/makna-kata': typeof MaknaKataRoute
  '/tutorial-install': typeof TutorialInstallRoute
  '/updater': typeof UpdaterRoute
  '/cari-makna': typeof GlosariumCariMaknaRoute
}
export interface FileRoutesByTo {
  '/makna-kata': typeof MaknaKataRoute
  '/tutorial-install': typeof TutorialInstallRoute
  '/updater': typeof UpdaterRoute
  '/cari-makna': typeof GlosariumCariMaknaRoute
  '/': typeof GlosariumIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_glosarium': typeof GlosariumRouteWithChildren
  '/makna-kata': typeof MaknaKataRoute
  '/tutorial-install': typeof TutorialInstallRoute
  '/updater': typeof UpdaterRoute
  '/_glosarium/cari-makna': typeof GlosariumCariMaknaRoute
  '/_glosarium/': typeof GlosariumIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/makna-kata'
    | '/tutorial-install'
    | '/updater'
    | '/cari-makna'
  fileRoutesByTo: FileRoutesByTo
  to: '/makna-kata' | '/tutorial-install' | '/updater' | '/cari-makna' | '/'
  id:
    | '__root__'
    | '/_glosarium'
    | '/makna-kata'
    | '/tutorial-install'
    | '/updater'
    | '/_glosarium/cari-makna'
    | '/_glosarium/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  GlosariumRoute: typeof GlosariumRouteWithChildren
  MaknaKataRoute: typeof MaknaKataRoute
  TutorialInstallRoute: typeof TutorialInstallRoute
  UpdaterRoute: typeof UpdaterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/updater': {
      id: '/updater'
      path: '/updater'
      fullPath: '/updater'
      preLoaderRoute: typeof UpdaterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutorial-install': {
      id: '/tutorial-install'
      path: '/tutorial-install'
      fullPath: '/tutorial-install'
      preLoaderRoute: typeof TutorialInstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/makna-kata': {
      id: '/makna-kata'
      path: '/makna-kata'
      fullPath: '/makna-kata'
      preLoaderRoute: typeof MaknaKataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_glosarium': {
      id: '/_glosarium'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GlosariumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_glosarium/': {
      id: '/_glosarium/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof GlosariumIndexRouteImport
      parentRoute: typeof GlosariumRoute
    }
    '/_glosarium/cari-makna': {
      id: '/_glosarium/cari-makna'
      path: '/cari-makna'
      fullPath: '/cari-makna'
      preLoaderRoute: typeof GlosariumCariMaknaRouteImport
      parentRoute: typeof GlosariumRoute
    }
  }
}

interface GlosariumRouteChildren {
  GlosariumCariMaknaRoute: typeof GlosariumCariMaknaRoute
  GlosariumIndexRoute: typeof GlosariumIndexRoute
}

const GlosariumRouteChildren: GlosariumRouteChildren = {
  GlosariumCariMaknaRoute: GlosariumCariMaknaRoute,
  GlosariumIndexRoute: GlosariumIndexRoute,
}

const GlosariumRouteWithChildren = GlosariumRoute._addFileChildren(
  GlosariumRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  GlosariumRoute: GlosariumRouteWithChildren,
  MaknaKataRoute: MaknaKataRoute,
  TutorialInstallRoute: TutorialInstallRoute,
  UpdaterRoute: UpdaterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
